[package]
name = "demo"
version = "0.1.0"
authors = ["ibanfi@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web="1.0"

[build]
target-dir = "../../target"